---
name: "Lint YAML Files"
on:
  pull_request:
    paths:
      - "**.yml"
      - "**.yaml"
  push:
    paths:
      - "**.yml"
      - "**.yaml"
jobs:
  yaml-lint:
    name: "YAML Lint"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - name: "Install yamllint"
        run: |
          python -m pip install --upgrade pip
          pip install yamllint
      - name: "Lint YAML files with strict rules"
        run: |
          echo "Running strict YAML linting..."
          yamllint -f parsable -c .yamllint .github/workflows/ 