name: goprox release action
run-name: ${{ github.actor }} is publishing release ${{ github.ref_name }}
on:
  release:
    types: [published]
jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest
    steps:
      - name: Dump env
        run: env | sort
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
  sha256:
    name: sha256
    runs-on: ubuntu-latest
    steps:
      - run: echo "https://github.com/fxstein/GoProX/archive/refs/tags/${{ github.ref_name }}.tar.gz"
      - run: curl -sL "https://github.com/fxstein/GoProX/archive/refs/tags/${{ github.ref_name }}.tar.gz" | shasum -a 256 | cut -d " " -f 1
