name: Version Bump Detection
on:
  push:
    branches: [main]
    paths: ['goprox']

jobs:
  detect-version-bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      
      - name: Check for version change
        id: version-check
        run: |
          PREV_VERSION=$(git show HEAD~1:goprox | grep "__version__=" | cut -d"'" -f2)
          CURR_VERSION=$(grep "__version__=" goprox | cut -d"'" -f2)
          
          echo "Previous version: $PREV_VERSION"
          echo "Current version: $CURR_VERSION"
          
          if [[ "$PREV_VERSION" != "$CURR_VERSION" ]]; then
            echo "version_changed=true" >> $GITHUB_OUTPUT
            echo "new_version=$CURR_VERSION" >> $GITHUB_OUTPUT
            echo "prev_version=$PREV_VERSION" >> $GITHUB_OUTPUT
            echo "Version changed from $PREV_VERSION to $CURR_VERSION"
          else
            echo "version_changed=false" >> $GITHUB_OUTPUT
            echo "No version change detected"
          fi
      
      - name: Trigger Release Process
        if: steps.version-check.outputs.version_changed == 'true'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "Triggering release automation for version ${{ steps.version-check.outputs.new_version }}"
          gh workflow run release-automation.yml \
            -f version=${{ steps.version-check.outputs.new_version }} \
            -f prev_version=${{ steps.version-check.outputs.prev_version }} \
            -f dry_run=false 